# This is a sample, non-production-ready template.
#
# © 2019 Amazon Web Services, In​c. or its affiliates. All Rights Reserved.
#
# This AWS Content is provided subject to the terms of the
# AWS Customer Agreement available at http://aws.amazon.com/agreement
# or other written agreement between Customer and either
# Amazon Web Services, Inc. or Amazon Web Services EMEA SARL or both.

AWSTemplateFormatVersion: "2010-09-09"
Description: >

    This template deploys the Gurum Platform Infrastructure together
    with the necessary exports for the Gurum Management API to integrate
    correctly.

    Modified By: Karl Wallbom <wallbomk@amazon.com>
    Author: Paul Maddox <pmaddox@amazon.com>

Parameters:

    PlatformDomainName:
        Type: AWS::SSM::Parameter::Value<String>
        Description: Gurum Platform Domain FQDN
        Default: /gurum/platform/domain-name

    ServiceDiscoveryDomainName:
        Description: Local service discovery DNS.
        Type: String
        Default: "gurum.local"

    # Defines if the template should create EC2 instances in the ECS cluster.
    # Leave this at 0 if you plan to only use Fargate.
    ClusterSize:
        Description: How many ECS hosts do you want to initially deploy?
        Type: Number
        Default: 0

    InstanceType:
        Description: Which instance type should we use to build the ECS cluster?
        Type: String
        Default: t3.medium

Conditions:

    ASGExists:
        !Not [!Equals [!Ref ClusterSize, "0"]]

Resources:

    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: cfn/vpc.yaml
            Parameters:
                EnvironmentName:    !Ref AWS::StackName
                VpcCIDR:            10.180.0.0/16
                PublicSubnet1CIDR:  10.180.8.0/21
                PublicSubnet2CIDR:  10.180.16.0/21
                PrivateSubnet1CIDR: 10.180.24.0/21
                PrivateSubnet2CIDR: 10.180.32.0/21

    ALB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: cfn/load-balancers.yaml
            Parameters:
                DomainName: !Ref PlatformDomainName
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC
                Subnets: !GetAtt VPC.Outputs.PublicSubnets

    ECS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: cfn/ecs-cluster.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                InstanceType: !Ref InstanceType
                ClusterSize: !Ref ClusterSize
                VPC: !GetAtt VPC.Outputs.VPC
                Subnets: !GetAtt VPC.Outputs.PrivateSubnets
                LoadBalancerSecurityGroup: !GetAtt ALB.Outputs.LoadBalancerSecurityGroup

    LifecycleHook:
        Type: AWS::CloudFormation::Stack
        Condition: ASGExists
        Properties:
            TemplateURL: cfn/lifecyclehook.yaml

    ServiceDiscovery:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: cfn/service-discovery.yaml
            Parameters:
                NamespaceName: !Ref ServiceDiscoveryDomainName
                VPC: !GetAtt VPC.Outputs.VPC

    ############################
    #      SSM Parameters      #
    ############################

    VPCParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gurum/platform/vpc"
            Type: "String"
            Value: !GetAtt VPC.Outputs.VPC
            Description: "Gurum Platform VPC ID."

    PublicSubnetsParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gurum/platform/subnets/public"
            Type: "StringList"
            Value: !GetAtt VPC.Outputs.PublicSubnets
            Description: "Gurum Platform Public Subnets."

    PrivateSubnetsParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gurum/platform/subnets/private"
            Type: "StringList"
            Value: !GetAtt VPC.Outputs.PrivateSubnets
            Description: "Gurum Platform Private Subnets."

    ServiceDiscoveryNamespaceParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gurum/platform/service-discovery/namespace"
            Type: "String"
            Value: !Ref ServiceDiscoveryDomainName
            Description: "Gurum Platform Service Discovery Namespace."

    NamespaceParam:
        Type: AWS::SSM::Parameter
        Properties:
            Name: /gurum/platform/service-discovery/namespace-id
            Type: String
            Value: !GetAtt ServiceDiscovery.Outputs.NamespaceId
            Description: Gurum Platform Namespace ID.

    PlatformDomainCertificate:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gurum/platform/domain-certificate"
            Type: "String"
            Value: !GetAtt ALB.Outputs.LoadBalancerListenerCertificate
            Description: "Gurum Platform Domain ACM Certificate."

    LoadBalancerDNSNameParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gurum/platform/loadbalancer/dns-name"
            Type: "String"
            Value: !GetAtt ALB.Outputs.LoadBalancerDNSName
            Description: "Gurum Platform Load Balancer DNS Name."

    LoadBalancerHostedZoneIdParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gurum/platform/loadbalancer/hosted-zone-id"
            Type: "String"
            Value: !GetAtt ALB.Outputs.LoadBalancerCanonicalHostedZoneID
            Description: "Gurum Platform Load Balancer Hosted Zone ID."

    LoadBalancerListenerArnParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gurum/platform/loadbalancer/listener-arn"
            Type: "String"
            Value: !GetAtt ALB.Outputs.LoadBalancerListener
            Description: "Gurum Platform Load Balancer Listener ARN."

    LoadBalancerSecurityGroupParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gurum/platform/loadbalancer/security-group"
            Type: "String"
            Value: !GetAtt ALB.Outputs.LoadBalancerSecurityGroup
            Description: "Gurum Platform Load Balancer Security Group."

    ECSClusterParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gurum/platform/ecs"
            Type: "String"
            Value: !GetAtt ECS.Outputs.ECSCluster
            Description: "Gurum Platform ECS Cluster."
