# This is a sample, non-production-ready template.
#
# © 2019 Amazon Web Services, In​c. or its affiliates. All Rights Reserved.
#
# This AWS Content is provided subject to the terms of the
# AWS Customer Agreement available at http://aws.amazon.com/agreement
# or other written agreement between Customer and either
# Amazon Web Services, Inc. or Amazon Web Services EMEA SARL or both.

AWSTemplateFormatVersion: "2010-09-09"
Description: >

    This template deploys the Gureume Platform Infrastructure together
    with the necessary exports for the Gureume Management API to integrate
    correctly.

    Modified By: Karl Wallbom <wallbomk@amazon.com>
    Author: Paul Maddox <pmaddox@amazon.com>

Parameters:

    PlatformDomainName:
        Type: AWS::SSM::Parameter::Value<String>
        Description: Gureume Platform Domain FQDN
        Default: /gureume/platform/domain-name

    ServiceDiscoveryDomainName:
        Description: Local service discovery DNS.
        Type: String
        Default: "gureume.local"

    # Defines if the template should create EC2 instances in the ECS cluster.
    # Leave this at 0 if you plan to only use Fargate.
    ClusterSize:
        Description: How many ECS hosts do you want to initially deploy?
        Type: Number
        Default: 0

Conditions:

    ASGExists:
        !Not [!Equals [!Ref ClusterSize, "0"]]

Resources:

    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: cfn/vpc.yaml
            Parameters:
                EnvironmentName:    !Ref AWS::StackName
                VpcCIDR:            10.180.0.0/16
                PublicSubnet1CIDR:  10.180.8.0/21
                PublicSubnet2CIDR:  10.180.16.0/21
                PrivateSubnet1CIDR: 10.180.24.0/21
                PrivateSubnet2CIDR: 10.180.32.0/21

    ALB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: cfn/load-balancers.yaml
            Parameters:
                DomainName: !Ref PlatformDomainName
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC
                Subnets: !GetAtt VPC.Outputs.PublicSubnets

    ECS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: cfn/ecs-cluster.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                InstanceType: t2.small
                ClusterSize: !Ref ClusterSize
                VPC: !GetAtt VPC.Outputs.VPC
                Subnets: !GetAtt VPC.Outputs.PrivateSubnets
                LoadBalancerSecurityGroup: !GetAtt ALB.Outputs.LoadBalancerSecurityGroup

    LifecycleHook:
        Type: AWS::CloudFormation::Stack
        Condition: ASGExists
        Properties:
            TemplateURL: cfn/lifecyclehook.yaml
            Parameters:
                Cluster: !GetAtt ECS.Outputs.Cluster
                ECSAutoScalingGroupName: !GetAtt ECS.Outputs.ECSAutoScalingGroupName

    ServiceDiscovery:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: cfn/service-discovery.yaml
            Parameters:
                NamespaceName: !Ref ServiceDiscoveryDomainName
                VPC: !GetAtt VPC.Outputs.VPC

    ############################
    #      SSM Parameters      #
    ############################

    VPCParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gureume/platform/vpc"
            Type: "String"
            Value: !GetAtt VPC.Outputs.VPC
            Description: "Gureume Platform VPC ID."
            Tags:
                "Environment": !Ref AWS::StackName

    PublicSubnetsParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gureume/platform/subnets/public"
            Type: "StringList"
            Value: !GetAtt VPC.Outputs.PublicSubnets
            Description: "Gureume Platform Public Subnets."
            Tags:
                "Environment": !Ref AWS::StackName

    PrivateSubnetsParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gureume/platform/subnets/private"
            Type: "StringList"
            Value: !GetAtt VPC.Outputs.PrivateSubnets
            Description: "Gureume Platform Private Subnets."
            Tags:
                "Environment": !Ref AWS::StackName

    ServiceDiscoveryNamespaceParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gureume/platform/service-discovery/namespace"
            Type: "String"
            Value: !Ref ServiceDiscoveryDomainName
            Description: "Gureume Platform Service Discovery Namespace."
            Tags:
                "Environment": !Ref AWS::StackName

    NamespaceParam:
        Type: AWS::SSM::Parameter
        Properties:
            Name: /gureume/platform/service-discovery/namespace-id
            Type: String
            Value: !GetAtt ServiceDiscovery.Outputs.NamespaceId
            Description: Gureume Platform Namespace ID.

    LoadBalancerDNSNameParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gureume/platform/loadbalancer/dns-name"
            Type: "String"
            Value: !GetAtt ALB.Outputs.LoadBalancerDNSName
            Description: "Gureume Platform Load Balancer DNS Name."
            Tags:
                "Environment": !Ref AWS::StackName

    LoadBalancerHostedZoneIdParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gureume/platform/loadbalancer/hosted-zone-id"
            Type: "String"
            Value: !GetAtt ALB.Outputs.LoadBalancerCanonicalHostedZoneID
            Description: "Gureume Platform Load Balancer Hosted Zone ID."
            Tags:
                "Environment": !Ref AWS::StackName

    LoadBalancerListenerArnParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gureume/platform/loadbalancer/listener-arn"
            Type: "String"
            Value: !GetAtt ALB.Outputs.LoadBalancerListener
            Description: "Gureume Platform Load Balancer Listener ARN."
            Tags:
                "Environment": !Ref AWS::StackName

    LoadBalancerSecurityGroupParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gureume/platform/loadbalancer/security-group"
            Type: "String"
            Value: !GetAtt ALB.Outputs.LoadBalancerSecurityGroup
            Description: "Gureume Platform Load Balancer Security Group."
            Tags:
                "Environment": !Ref AWS::StackName

    ECSClusterParam:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: "/gureume/platform/ecs"
            Type: "String"
            Value: !GetAtt ECS.Outputs.ECSCluster
            Description: "Gureume Platform ECS Cluster."
            Tags:
                "Environment": !Ref AWS::StackName