# This is a sample, non-production-ready template.
#
# © 2019 Amazon Web Services, In​c. or its affiliates. All Rights Reserved.
#
# This AWS Content is provided subject to the terms of the
# AWS Customer Agreement available at http://aws.amazon.com/agreement
# or other written agreement between Customer and either
# Amazon Web Services, Inc. or Amazon Web Services EMEA SARL or both.

AWSTemplateFormatVersion: 2010-09-09
Description: >

  This template deploys the Gurum Platform Infrastructure together
  with the necessary exports for the Gurum Management API to integrate
  correctly.

  Author: Karl Wallbom <wallbomk@amazon.com>

Parameters:
  PlatformDomainName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Gurum Platform Domain FQDN
    Default: /gurum/platform/domain-name

  ServiceDiscoveryDomainName:
    Description: Local service discovery DNS.
    Type: String
    Default: gurum.local

  # Defines if the template should create EC2 instances in the ECS cluster.
  # Leave this at 0 if you plan to only use Fargate.
  EcsClusterMaxSize:
    Description: What's the maximum number of instances the EC2 ASG can scale to?
    Type: Number
    Default: 0

  EcsInstanceType:
    Description: Which instance type should we use to build the ECS cluster?
    Type: String
    Default: t3.medium

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cfn/vpc.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName

  ServiceDiscovery:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cfn/service-discovery.yaml
      Parameters:
        DomainName: !Ref PlatformDomainName
        ServiceDiscoveryDomainName: !Ref ServiceDiscoveryDomainName
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VpcId
        Subnets: !GetAtt VPC.Outputs.PublicSubnets

  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cfn/ecs-cluster.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        EcsInstanceType: !Ref EcsInstanceType
        EcsClusterMaxSize: !Ref EcsClusterMaxSize
        VPC: !GetAtt VPC.Outputs.VpcId
        Subnets: !GetAtt VPC.Outputs.PrivateSubnets
        LoadBalancerSecurityGroup: !GetAtt ServiceDiscovery.Outputs.LoadBalancerSecurityGroup
