AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Backing Service

Parameters:

  ServiceBindings:
    Description: Comma-separated list for role names to add permissions to
    Type: String

Resources:

  S3Bucket:
    Type: 'AWS::S3::Bucket'

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: Policy
        Version: 2012-10-17
        Statement:
          - Sid: ReadWriteFromApp
            Effect: Allow
            Principal:
              AWS: !Split
                - ','
                - !Sub
                  - 'arn:aws:iam::${AWS::AccountId}:role/platform-role-${ServiceBindingsList}'
                  - ServiceBindingsList: !Join [',', [ !Ref ServiceBindings ] ]
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Resource: !Sub arn:${AWS::Partition}:s3:::${S3Bucket}/*
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: '*'
            Action: s3:PutObject
            Resource: !Sub arn:${AWS::Partition}:s3:::${S3Bucket}/*
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption:
                  - AES256
                  - aws:kms
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource: !Sub arn:${AWS::Partition}:s3:::${S3Bucket}/*
            Condition:
              Bool:
                aws:SecureTransport: false
      Bucket: !Ref S3Bucket

Outputs:
  ServiceArn:
    Value: !GetAtt S3Bucket.Arn