# This is a sample, non-production-ready template.
#
# © 2019 Amazon Web Services, In​c. or its affiliates. All Rights Reserved.
#
# This AWS Content is provided subject to the terms of the
# AWS Customer Agreement available at http://aws.amazon.com/agreement
# or other written agreement between Customer and either
# Amazon Web Services, Inc. or Amazon Web Services EMEA SARL or both.

AWSTemplateFormatVersion: "2010-09-09"
Description: >
    This template deploys a namespace for using ECS Service Discovery together with the Route 53 Auto Naming API

Parameters:

    NamespaceName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    VPC:
        Description: VPC to attach the private namespace to
        Type: AWS::EC2::VPC::Id

Resources:

  Namespace:
    Type: "AWS::ServiceDiscovery::PrivateDnsNamespace"
    Properties:
      Description: Service Discovery Namespace for Platform
      Vpc: !Ref VPC
      Name: !Ref NamespaceName

Outputs:

    NamespaceName:
        Description: Service Discovery Namespace Name
        Value: !Ref NamespaceName

    NamespaceId:
        Description: Service Discovery Namespace ID
        Value: !GetAtt Namespace.Id